# -*- coding: utf-8 -*-
"""Tool: R10/F10 Firmware Advanced Settings.

Provides category-based configuration for custom CoreELEC / Amlogic firmware
advanced settings (ALSA sink, hardware decoding, VC-1, Mali EGL pipeline,
dirty regions, network timeouts, and Blu-ray ISO block cache).
"""

from typing import Any, Dict, List, Optional

CATEGORIES: List[Dict[str, Any]] = [
    {
        "id": "audio",
        "title_id": 31002,
        "desc": "Audio Engine & ALSA Sink",
    },
    {
        "id": "video",
        "title_id": 31003,
        "desc": "Video Player & Hardware Codec",
    },
    {
        "id": "gui",
        "title_id": 31004,
        "desc": "GUI Rendering & Mali EGL Pipeline",
    },
    {
        "id": "videolibrary",
        "title_id": 31005,
        "desc": "Video Library Management",
    },
    {
        "id": "network",
        "title_id": 31006,
        "desc": "LAN Protocols & NFS",
    },
    {
        "id": "database",
        "title_id": 31007,
        "desc": "Remote Database Connect Timeout",
    },
    {
        "id": "blurayisocache",
        "title_id": 31008,
        "desc": "Blu-ray ISO Block Cache",
    },
]

SETTINGS_SCHEMA: List[Dict[str, Any]] = [
    # 1. Audio Engine & ALSA Sink
    {
        "id": "pcmsinkbitsmax",
        "category": "audio",
        "section": "audio",
        "tag": "pcmsinkbitsmax",
        "type": "choice",
        "default": "0",
        "title_id": 31030,
        "desc_id": 31031,
        "help_id": 31032,
        "choices": ["0", "16", "24", "32"],
    },
    {
        "id": "sinksettleholdms",
        "category": "audio",
        "section": "audio",
        "tag": "sinksettleholdms",
        "type": "int",
        "default": "0",
        "title_id": 31033,
        "desc_id": 31034,
        "help_id": 31035,
        "range": (0, 2000),
        "unit": "ms",
    },

    # 2. Video Player & Hardware Codec
    {
        "id": "menudomainqueuetimesize",
        "category": "video",
        "section": "video",
        "tag": "menudomainqueuetimesize",
        "type": "float",
        "default": "1.0",
        "title_id": 31040,
        "desc_id": 31041,
        "help_id": 31042,
        "range": (0.0, 16.0),
        "unit": "s",
    },
    {
        "id": "bdboundarydrain",
        "category": "video",
        "section": "video",
        "tag": "bdboundarydrain",
        "type": "bool",
        "default": "true",
        "title_id": 31043,
        "desc_id": 31044,
        "help_id": 31045,
    },
    {
        "id": "subtitleasyncparse",
        "category": "video",
        "section": "video",
        "tag": "subtitleasyncparse",
        "type": "bool",
        "default": "true",
        "title_id": 31046,
        "desc_id": 31047,
        "help_id": 31048,
    },
    {
        "id": "asyncfullscreenosd",
        "category": "video",
        "section": "video",
        "tag": "asyncfullscreenosd",
        "type": "choice",
        "default": "2",
        "title_id": 31049,
        "desc_id": 31050,
        "help_id": 31051,
        "choices": ["0", "1", "2"],
    },
    {
        "id": "asyncvideolayerrender",
        "category": "video",
        "section": "video",
        "tag": "asyncvideolayerrender",
        "type": "bool",
        "default": "true",
        "title_id": 31052,
        "desc_id": 31053,
        "help_id": 31054,
    },
    {
        "id": "seekminimumdistancebeforeeof",
        "category": "video",
        "section": "video",
        "tag": "seekminimumdistancebeforeeof",
        "type": "int",
        "default": "10",
        "title_id": 31055,
        "desc_id": 31056,
        "help_id": 31057,
        "range": (0, 600),
        "unit": "s",
    },
    {
        "id": "dvvsvdbv1",
        "category": "video",
        "section": "video",
        "tag": "dvvsvdbv1",
        "type": "bool",
        "default": "false",
        "title_id": 31058,
        "desc_id": 31059,
        "help_id": 31060,
    },
    {
        "id": "deinterlacedelaycompensation",
        "category": "video",
        "section": "video",
        "tag": "deinterlacedelaycompensation",
        "type": "bool",
        "default": "false",
        "title_id": 31061,
        "desc_id": 31062,
        "help_id": 31063,
    },
    {
        "id": "videoratefieldhold",
        "category": "video",
        "section": "video",
        "tag": "videoratefieldhold",
        "type": "bool",
        "default": "true",
        "title_id": 31064,
        "desc_id": 31065,
        "help_id": 31066,
    },
    {
        "id": "vc1forceframeint",
        "category": "video",
        "section": "video",
        "tag": "vc1forceframeint",
        "type": "bool",
        "default": "true",
        "title_id": 31067,
        "desc_id": 31068,
        "help_id": 31069,
    },
    {
        "id": "vc1dropframe",
        "category": "video",
        "section": "video",
        "tag": "vc1dropframe",
        "type": "bool",
        "default": "true",
        "title_id": 31070,
        "desc_id": 31071,
        "help_id": 31072,
    },
    {
        "id": "vc1repairtimestamps",
        "category": "video",
        "section": "video",
        "tag": "vc1repairtimestamps",
        "type": "bool",
        "default": "true",
        "title_id": 31073,
        "desc_id": 31074,
        "help_id": 31075,
    },

    # 3. GUI Rendering & Mali EGL Pipeline
    {
        "id": "bufferagepartialredraw",
        "category": "gui",
        "section": "gui",
        "tag": "bufferagepartialredraw",
        "type": "choice",
        "default": "1",
        "title_id": 31080,
        "desc_id": 31081,
        "help_id": 31082,
        "choices": ["0", "1"],
    },
    {
        "id": "bufferageafterrenderscope",
        "category": "gui",
        "section": "gui",
        "tag": "bufferageafterrenderscope",
        "type": "bool",
        "default": "true",
        "title_id": 31083,
        "desc_id": 31084,
        "help_id": 31085,
    },
    {
        "id": "maxdirtyregions",
        "category": "gui",
        "section": "gui",
        "tag": "maxdirtyregions",
        "type": "int",
        "default": "4",
        "title_id": 31086,
        "desc_id": 31087,
        "help_id": 31088,
        "range": (0, 64),
    },
    {
        "id": "skipsleepactivewindow",
        "category": "gui",
        "section": "gui",
        "tag": "skipsleepactivewindow",
        "type": "int",
        "default": "250",
        "title_id": 31089,
        "desc_id": 31090,
        "help_id": 31091,
        "range": (0, 2000),
        "unit": "ms",
    },
    {
        "id": "menuidleframeratecap",
        "category": "gui",
        "section": "gui",
        "tag": "menuidleframeratecap",
        "type": "int",
        "default": "0",
        "title_id": 31092,
        "desc_id": 31093,
        "help_id": 31094,
        "range": (0, 60),
        "unit": "FPS",
    },
    {
        "id": "skinhdrfbo",
        "category": "gui",
        "section": "gui",
        "tag": "skinhdrfbo",
        "type": "choice",
        "default": "0",
        "title_id": 31095,
        "desc_id": 31096,
        "help_id": 31097,
        "choices": ["0", "1"],
    },
    {
        "id": "osdguestcomposite",
        "category": "gui",
        "section": "gui",
        "tag": "osdguestcomposite",
        "type": "choice",
        "default": "0",
        "title_id": 31098,
        "desc_id": 31099,
        "help_id": 31100,
        "choices": ["0", "1"],
    },
    {
        "id": "osdtrace",
        "category": "gui",
        "section": "gui",
        "tag": "osdtrace",
        "type": "choice",
        "default": "0",
        "title_id": 31101,
        "desc_id": 31102,
        "help_id": 31103,
        "choices": ["0", "1"],
    },
    {
        "id": "anisotropicfiltering",
        "category": "gui",
        "section": "gui",
        "tag": "anisotropicfiltering",
        "type": "choice",
        "default": "0",
        "title_id": 31104,
        "desc_id": 31105,
        "help_id": 31106,
        "choices": ["0", "2", "4", "8", "16"],
    },
    {
        "id": "fronttobackrendering",
        "category": "gui",
        "section": "gui",
        "tag": "fronttobackrendering",
        "type": "bool",
        "default": "false",
        "title_id": 31107,
        "desc_id": 31108,
        "help_id": 31109,
    },
    {
        "id": "geometryclear",
        "category": "gui",
        "section": "gui",
        "tag": "geometryclear",
        "type": "bool",
        "default": "true",
        "title_id": 31110,
        "desc_id": 31111,
        "help_id": 31112,
    },
    {
        "id": "waitvsyncbeforeswap",
        "category": "gui",
        "section": "gui",
        "tag": "waitvsyncbeforeswap",
        "type": "bool",
        "default": "true",
        "title_id": 31113,
        "desc_id": 31114,
        "help_id": 31115,
    },
    {
        "id": "waitgpubeforeswap",
        "category": "gui",
        "section": "gui",
        "tag": "waitgpubeforeswap",
        "type": "choice",
        "default": "2",
        "title_id": 31116,
        "desc_id": 31117,
        "help_id": 31118,
        "choices": ["0", "1", "2"],
    },
    {
        "id": "srgbhdrcomposite",
        "category": "gui",
        "section": "gui",
        "tag": "srgbhdrcomposite",
        "type": "bool",
        "default": "true",
        "title_id": 31119,
        "desc_id": 31120,
        "help_id": 31121,
    },
    {
        "id": "compositedither",
        "category": "gui",
        "section": "gui",
        "tag": "compositedither",
        "type": "bool",
        "default": "true",
        "title_id": 31122,
        "desc_id": 31123,
        "help_id": 31124,
    },
    {
        "id": "asynctextureupload",
        "category": "gui",
        "section": "gui",
        "tag": "asynctextureupload",
        "type": "bool",
        "default": "true",
        "title_id": 31125,
        "desc_id": 31126,
        "help_id": 31127,
    },
    {
        "id": "mipmapping",
        "category": "gui",
        "section": "gui",
        "tag": "mipmapping",
        "type": "bool",
        "default": "false",
        "title_id": 31128,
        "desc_id": 31129,
        "help_id": 31130,
    },
    {
        "id": "mipmappingsharpen",
        "category": "gui",
        "section": "gui",
        "tag": "mipmappingsharpen",
        "type": "float",
        "default": "0.5",
        "title_id": 31131,
        "desc_id": 31132,
        "help_id": 31133,
        "range": (0.0, 3.0),
    },
    {
        "id": "minifiedmipmapping",
        "category": "gui",
        "section": "gui",
        "tag": "minifiedmipmapping",
        "type": "bool",
        "default": "true",
        "title_id": 31134,
        "desc_id": 31135,
        "help_id": 31136,
    },

    # 4. Video Library Management
    {
        "id": "casesensitivelocalartmatch",
        "category": "videolibrary",
        "section": "videolibrary",
        "tag": "casesensitivelocalartmatch",
        "type": "bool",
        "default": "true",
        "title_id": 31137,
        "desc_id": 31138,
        "help_id": 31139,
    },

    # 5. LAN Protocols & NFS
    {
        "id": "nfstimeout",
        "category": "network",
        "section": "network",
        "tag": "nfstimeout",
        "type": "int",
        "default": "0",
        "title_id": 31140,
        "desc_id": 31141,
        "help_id": 31142,
        "range": (0, 3600),
        "unit": "s",
    },
    {
        "id": "nfsretries",
        "category": "network",
        "section": "network",
        "tag": "nfsretries",
        "type": "int",
        "default": "-1",
        "title_id": 31143,
        "desc_id": 31144,
        "help_id": 31145,
        "range": (-1, 30),
    },

    # 6. Remote Database Connect Timeout (multi-parent mapping)
    {
        "id": "db_connecttimeout",
        "category": "database",
        "section": ["videodatabase", "musicdatabase", "tvdatabase", "epgdatabase"],
        "tag": "connecttimeout",
        "type": "int",
        "default": "5",
        "title_id": 31146,
        "desc_id": 31147,
        "help_id": 31148,
        "range": (1, 60),
        "unit": "s",
    },

    # 7. Blu-ray ISO Block Cache
    {
        "id": "pagesize",
        "category": "blurayisocache",
        "section": "blurayisocache",
        "tag": "pagesize",
        "type": "int",
        "default": "262144",
        "title_id": 31149,
        "desc_id": 31150,
        "help_id": 31151,
        "range": (65536, 1048576),
        "unit": "bytes",
    },
    {
        "id": "maxbytes",
        "category": "blurayisocache",
        "section": "blurayisocache",
        "tag": "maxbytes",
        "type": "int",
        "default": "67108864",
        "title_id": 31152,
        "desc_id": 31153,
        "help_id": 31154,
        "range": (16777216, 536870912),
        "unit": "bytes",
    },
    {
        "id": "forwardprefetchpages",
        "category": "blurayisocache",
        "section": "blurayisocache",
        "tag": "forwardprefetchpages",
        "type": "int",
        "default": "1",
        "title_id": 31155,
        "desc_id": 31156,
        "help_id": 31157,
        "range": (0, 16),
    },
]


def get_setting_by_id(setting_id: str) -> Optional[Dict[str, Any]]:
    """Look up setting schema item by its unique ID."""
    for item in SETTINGS_SCHEMA:
        if item["id"] == setting_id:
            return item
    return None


def get_settings_by_category(category_id: str) -> List[Dict[str, Any]]:
    """Retrieve all setting schema items in a given category."""
    return [item for item in SETTINGS_SCHEMA if item["category"] == category_id]
